import { NgModule } from '@angular/core';
import {
  IconBriefcase,
  IconBookOpen,
  IconShoppingBag,
  // -------
  IconTrash2,
  IconUser,
  IconGithub,
  IconPlus,
  IconMail,
  IconMap,
  IconDollarSign,
  IconCalendar,
  IconSmartphone,
  IconLinkedin,
  IconImage,
  IconBell,
  IconMenu,
  IconBellOff,
  IconXSquare,
  IconPhone,
  IconHelpCircle,
  IconSearch,
  IconX,
  IconChevronDown,
  IconShoppingCart,
  IconMinus,
  IconArrowLeft,
  IconCheck,
  IconCreditCard,
  IconSlash,
  IconLoader,
  IconInfo,
  IconLock,
  IconGlobe,
  IconEdit,
  IconAlertCircle,
  IconHeart,
  IconTrendingDown,
  IconPlay,
  IconUsers,
  IconFacebook,
  IconStar,
  IconShare,
  IconHome,
  IconInstagram
} from 'angular-feather';

const icons = [
  IconBriefcase,
  IconBookOpen,
  IconShoppingBag,
  IconUser,
  IconFacebook,
  IconInstagram,
  // ------------
  IconUser,
  IconTrash2,
  IconGithub,
  IconPlus,
  IconMail,
  IconMap,
  IconDollarSign,
  IconCalendar,
  IconSmartphone,
  IconLinkedin,
  IconImage,
  IconBell,
  IconMenu,
  IconBellOff,
  IconXSquare,
  IconPhone,
  IconHelpCircle,
  IconSearch,
  IconX,
  IconChevronDown,
  IconShoppingCart,
  IconMinus,
  IconArrowLeft,
  IconCheck,
  IconCreditCard,
  IconSlash,
  IconLoader,
  IconInfo,
  IconLock,
  IconGlobe,
  IconEdit,
  IconAlertCircle,
  IconHeart,
  IconTrendingDown,
  IconPlay,
  IconUsers,
  IconFacebook,
  IconStar,
  IconShare,
  IconHome
];

@NgModule({
  exports: icons
})
export class IconsModule { }
